name: Python Test Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Check out repository
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests

    # Upload test results to GitHub (optional)
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: tests/test_results.xml
